#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
export PATH=$HOME/bin:/usr/local/bin:$PATH
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# echo "Binding keys...."
# bindkey "\e\e[D" emacs-backward-word
# bindkey "\e\e[C" emacs-forward-word
# bindkey "\x0f" beginning-of-line
# bindkey "\x1f" end-of-line
# bindkey "\x9f" backward-kill-line
# bindkey "\x90" backward-kill-word

. $HOME/.asdf/asdf.sh

. $HOME/.asdf/completions/asdf.bash
