#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

export PATH="/Applications/Sublime Text.app/Contents/SharedSupport/bin:$PATH"

# Customize to your needs...
# if [[ $OSTYPE == darwin* && $CPUTYPE != arm64 ]]; then
#   alias brew=/usr/local/homebrew/bin/brew
#   export PATH="/usr/local/opt/curl/bin:/usr/local/opt/openssl@1.1/bin:$HOME/bin:$PATH"

#   export LDFLAGS="-L/usr/local/opt/openssl@1.1/lib"
#   export CPPFLAGS="-I/usr/local/opt/openssl@1.1/include"
# fi

# if [[ $OSTYPE == darwin* && $CPUTYPE == arm64 ]]; then
#   alias brew=/opt/homebrew/bin/brew
#   export PATH="/opt/homebrew/bin:/opt/homebrew/opt/openssl@1.1/bin:/usr/local/aws-cli:$PATH"

#   export LDFLAGS="-L/opt/homebrew/opt/openssl@1.1/lib"
#   export CPPFLAGS="-I/opt/homebrew/opt/openssl@1.1/include"
# fi
# export LC_ALL=en_US.UTF-8
# export LANG=en_US.UTF-8




# echo "Binding keys...."
# bindkey "\e\e[D" emacs-backward-word
# bindkey "\e\e[C" emacs-forward-word
# bindkey "\x0f" beginning-of-line
# bindkey "\x1f" end-of-line
# bindkey "\x9f" backward-kill-line
# bindkey "\x90" backward-kill-word

. $HOME/.asdf/asdf.sh

# append completions to fpath
fpath=(${ASDF_DIR}/completions $fpath)
# initialise completions with ZSH's compinit
autoload -Uz compinit
compinit

#function inspect SSL certs through commandline
function seecert () {
  nslookup $1
  (openssl s_client -showcerts -servername $1 -connect $1:443 <<< "Q" | openssl x509 -text | grep -iA2 "Validity")
}

# export KERL_CONFIGURE_OPTIONS="--disable-debug --disable-silent-rules --disable-sctp --without-javac --enable-shared-zlib --enable-dynamic-ssl-lib --enable-hipe --enable-smp-support --enable-threads --enable-kernel-poll --enable-wx --enable-darwin-64bit --with-ssl=$(brew --prefix openssl@1.1)"

export ERL_AFLAGS="-kernel shell_history enabled"
